### ISSUE TITLE
malloc_consolidate(): invalid chunk size

### ISSUE THREAD

**Issue by serzhiio** [async-email/async-native-tls#11]
```
Thread 7 "async-std/execu" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff74b7700 (LWP 11374)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7a61535 in __GI_abort () at abort.c:79
#2  0x00007ffff7ab8508 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7bc328d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff7abec1a in malloc_printerr (str=str@entry=0x7ffff7bc4b68 "malloc_consolidate(): invalid chunk size") at malloc.c:5341
#4  0x00007ffff7abef2a in malloc_consolidate (av=av@entry=0x7fffec000020) at malloc.c:4471
#5  0x00007ffff7ac1a58 in _int_malloc (av=av@entry=0x7fffec000020, bytes=bytes@entry=16712) at malloc.c:3695
#6  0x00007ffff7ac356a in __GI___libc_malloc (bytes=16712) at malloc.c:3057
#7  0x00007ffff7f5ba3c in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#8  0x00007ffff7f5b118 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#9  0x00007ffff7f62265 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#10 0x00007ffff7f6ccfa in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.1
#11 0x00007ffff7f6ce03 in SSL_read () from /lib/x86_64-linux-gnu/libssl.so.1.1
#12 0x0000555555a44bc1 in openssl::ssl::SslRef::read (self=0x7fffec267e00, buf=...) at /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.26/src/ssl/mod.rs:2369
#13 0x0000555555767af9 in openssl::ssl::SslStream<S>::ssl_read (self=0x7fffe800a240, buf=...)
    at /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.26/src/ssl/mod.rs:3408
#14 0x00005555557669cd in <openssl::ssl::SslStream<S> as std::io::Read>::read (self=0x7fffe800a240, buf=...)
    at /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.26/src/ssl/mod.rs:3550
#15 0x000055555578f1d0 in <native_tls::imp::TlsStream<S> as std::io::Read>::read (self=0x7fffe800a240, buf=...)
    at /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/native-tls-0.2.3/src/imp/openssl.rs:396
#16 0x00005555557567f0 in <native_tls::TlsStream<S> as std::io::Read>::read (self=0x7fffe800a240, buf=...)
    at /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/native-tls-0.2.3/src/lib.rs:649
#17 0x00005555556f2749 in <async_native_tls::tls_stream::TlsStream<S> as futures_io::if_std::AsyncRead>::poll_read::{{closure}} (s=0x7fffe800a240)
    at /home/debian/.cargo/git/checkouts/async-native-tls-f8ca429da40dea5c/f995a78/src/tls_stream.rs:63
#18 0x00005555556f1df3 in async_native_tls::tls_stream::TlsStream<S>::with_context (self=0x7fffe800a240, ctx=0x7ffff74b6148, f=...)
    at /home/debian/.cargo/git/checkouts/async-native-tls-f8ca429da40dea5c/f995a78/src/tls_stream.rs:34
#19 0x00005555556f26fc in <async_native_tls::tls_stream::TlsStream<S> as futures_io::if_std::AsyncRead>::poll_read (self=..., ctx=0x7ffff74b6148, buf=...)
    at /home/debian/.cargo/git/checkouts/async-native-tls-f8ca429da40dea5c/f995a78/src/tls_stream.rs:63
#20 0x0000555555785683 in <futures_util::io::split::ReadHalf<R> as futures_io::if_std::AsyncRead>::poll_read::{{closure}} (l=..., cx=0x7ffff74b6148)
    at /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/io/split.rs:39
#21 0x00005555557853ae in futures_util::io::split::lock_and_then (lock=0x7fffe8034d40, cx=0x7ffff74b6148, f=...)
    at /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/io/split.rs:27
#22 0x000055555578562c in <futures_util::io::split::ReadHalf<R> as futures_io::if_std::AsyncRead>::poll_read (self=..., cx=0x7ffff74b6148, buf=...)
    at /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/io/split.rs:39
#23 0x00005555557855c0 in <&mut T as futures_io::if_std::AsyncRead>::poll_read (self=..., cx=0x7ffff74b6148, buf=...)
    at /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-io-0.3.1/src/lib.rs:321
#24 0x000055555576af52 in <futures_util::io::read::Read<R> as core::future::future::Future>::poll (self=..., cx=0x7ffff74b6148)
    at /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.1/src/io/read.rs:28
```

**Comment by dignifiedquire** [comment]
From chat it looks like this was a bug in the user code, so closing this for now.
